from models.arima_model import predict_arima, generate_historical_predictions as generate_arima_predictions
from models.moving_average_model import predict_ma, generate_historical_predictions as generate_ma_predictions
from models.prophet_model import predict_prophet, generate_historical_predictions as generate_prophet_predictions
from models.exponential_smoothing_model import predict_exp_smoothing, generate_historical_predictions as generate_exp_smoothing_predictions
from models.regression_model import predict_regression, generate_historical_predictions as generate_regression_predictions
from models.naive_model import predict_naive, generate_historical_predictions as generate_naive_predictions
from models.ar_model import predict_ar2, generate_historical_predictions as generate_ar2_predictions
